# Generated by Django 3.2.12 on 2024-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='adresse',
            field=models.CharField(default='Conakry', max_length=50),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='genre',
            field=models.BooleanField(default=True),
        ),
    ]
