# Generated by Django 5.0.4 on 2024-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_membresequipe_facebook_membresequipe_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalcours',
            name='amelioration_aspects',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='appreciation_global',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='aspect_eval',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='climat_cours',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='comment_tavaux_eval',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='condition_materiel',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='correppondance_matetplan',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='delai_correction_travaux',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='disponibilite_prof',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='doc_accompagne',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='dynamisme_enthousiasme_prof',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='expression_prof',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='interet_cours',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='nombre_etud_propice',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='plan_cours',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='planing_sceance',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='points_forts',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='prepa_leçon',
            field=models.TextField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')]),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='pres_modalite_eval',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='presentation_cours',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='remarques_precisions_suggestions',
            field=models.TextField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='respect_etudiant',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='respect_horaire',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='sentiment_equite',
            field=models.CharField(choices=[('Totalement en Désaccord', 'Totalement en Désaccord'), ('En Désaccord', 'En Désaccord'), ('Plutot en Désaccord', 'Plutot en Désaccord'), ("D'accord", "D'accord"), ("Plutôt D'accord", "Plutôt D'accord"), ("Tout à fait D'accord", "Tout à fait D'accord"), ('Aucun Avis', 'Aucun Avis')], max_length=50, null=True),
        ),
    ]
