# Generated by Django 5.0.4 on 2024-05-14 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20240506_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Application.departement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='ecole_origine',
            field=models.CharField(default='Tito', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='ine',
            field=models.CharField(default=234523, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='licence',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Application.licence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(default='Gueckedou', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mere',
            field=models.CharField(default='dofj', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='pere',
            field=models.CharField(default='lsdkf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='pv',
            field=models.CharField(default=344, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
