# Generated by Django 5.0.4 on 2024-05-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_etudiant_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='is_etudiant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='is_professeur',
            field=models.BooleanField(default=True),
        ),
    ]
