# Generated by Django 5.0.6 on 2024-08-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_evalcours_amelioration_aspects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalcours',
            name='prepa_leçon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evalcours',
            name='remarques_precisions_suggestions',
            field=models.TextField(null=True),
        ),
    ]
