# Generated by Django 5.0.6 on 2024-08-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_alter_evalcours_prepa_leçon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalcours',
            name='cours',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='Application.matiere'),
            preserve_default=False,
        ),
    ]
