# Generated by Django 5.0.4 on 2024-05-15 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_alter_etudiant_user_alter_professeur_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='Nom',
            field=models.CharField(default='Ety', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Prenom',
            field=models.CharField(default='kam', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='is_etudiant',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='is_professeur',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
