# Generated by Django 5.0.6 on 2024-08-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_evalcours_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalcours',
            name='cours',
            field=models.CharField(max_length=150),
        ),
    ]
