# Generated by Django 5.0.4 on 2024-05-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_etudiant_nom_etudiant_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='Prenom',
        ),
    ]
