# Generated by Django 5.0.4 on 2024-05-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_alter_etudiant_user_alter_matiere_professeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.professeur'),
        ),
    ]
