# Generated by Django 5.0.4 on 2024-05-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_alter_matiere_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='competence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
