# Generated by Django 5.0.4 on 2024-05-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_professeur_competence_professeur_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='email',
        ),
        migrations.CreateModel(
            name='AncienSujets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ancien_sujets')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=255, null=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.matiere')),
                ('membres', models.ManyToManyField(to='Application.etudiant')),
            ],
        ),
    ]
