# Generated by Django 5.0.4 on 2024-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_remove_professeur_email_anciensujets_projets'),
    ]

    operations = [
        migrations.AddField(
            model_name='anciensujets',
            name='annee',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
