# Generated by Django 5.0.4 on 2024-05-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_alter_notes_etudiant_alter_presence_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
