# Generated by Django 5.0.4 on 2024-05-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_opportunite_date_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='titre',
            field=models.CharField(default='Orange Guinée Récrute un Stagiaire', max_length=200),
            preserve_default=False,
        ),
    ]
