# Generated by Django 5.0.4 on 2024-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_opportunite_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='slug',
            field=models.SlugField(default='orange-guinee-recrute'),
            preserve_default=False,
        ),
    ]
