# Generated by Django 5.0.4 on 2024-06-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_opportunite_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='is_etudiant',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='is_professeur',
        ),
    ]
